# Exercício-Programa 2: Resolvendo a Equação de Calor em Estado Estacionário Usando CUDA

Este jupyter notebook realiza o *parsing* dos relatórios gerados por `run_measurements.sh`, concatena todos resultados em um único dataframe e gera o `.csv` final.

In [7]:
def get_file_paths(dir_path='measurements'):
    import os

    reports = ['jacobi_iteration.txt', 'cuda_jacobi_iteration.txt']
    
    paths = []
    for report in reports:
        paths.append(os.path.join(dir_path, report))

    return paths

In [63]:
import numpy as np
import pandas as pd
import re
import math

def parse_reports(reports):
    names = {
        'heat': 'sequential',
        'cuda_heat': 'cuda',
    }
    
    regex = r"\./(\w+)\.o (\d+) (\d+)(?: (\d+) (\d+))?\nTempo de execução: ([\d.]+) segundos"
    
    data = []

    # Extracting matched values from report using the regular expressions
    for report in reports:
        match = re.match(regex, report)
        if match:
            executable, n_points, iter_limit, num_threads, num_blocks, elapsed_time = match.groups()
            block_size = int(math.sqrt(int(num_threads))) if num_threads else np.nan
            grid_dim = ((int(n_points) + block_size - 1)/block_size) if num_blocks else np.nan
            data.append({
                "executable": executable,
                "n_points": int(n_points),
                "iter_limit": int(iter_limit),
                "block_dim_x": block_size,
                "block_dim_y": block_size,
                "grid_dim_x": grid_dim,
                "grid_dim_y": grid_dim,
                "num_threads_per_block": int(num_threads) if num_threads else np.nan,
                "num_blocks_per_grid": int(num_blocks) if num_blocks else np.nan,
                "elapsed_time": float(elapsed_time)
            })

    df = pd.DataFrame(data)
    df['version'] = df['executable'].replace(names)

    return df

In [64]:
def read_and_parse_reports(file_paths):
    reports = ""
    for file_path in file_paths:
        f = open(file_path, 'r')
        reports += f.read()
        f.close()

    # print(reports)
    reports = reports.split("\n\n")
    df = parse_reports(reports)
    return df

In [65]:
paths = get_file_paths()
dataframes = []

dataframe = read_and_parse_reports(paths)

NameError: name 'tmath' is not defined

In [61]:
dataframe[0:10]

,executable,n_points,iter_limit,block_dim_x,block_dim_y,grid_dim_x,grid_dim_y,num_threads_per_block,num_blocks_per_grid,elapsed_time,version
0,heat,100,1024,NaN,NaN,NaN,NaN,NaN,NaN,0.019029,sequential
1,heat,100,1024,NaN,NaN,NaN,NaN,NaN,NaN,0.011628,sequential
2,heat,100,1024,NaN,NaN,NaN,NaN,NaN,NaN,0.011909,sequential
3,heat,100,1024,NaN,NaN,NaN,NaN,NaN,NaN,0.011505,sequential
4,heat,100,1024,NaN,NaN,NaN,NaN,NaN,NaN,0.012634,sequential
5,heat,100,1024,NaN,NaN,NaN,NaN,NaN,NaN,0.012107,sequential
6,heat,100,1024,NaN,NaN,NaN,NaN,NaN,NaN,0.022169,sequential
7,heat,100,1024,NaN,NaN,NaN,NaN,NaN,NaN,0.022442,sequential
8,heat,100,1024,NaN,NaN,NaN,NaN,NaN,NaN,0.011726,sequential
9,heat,100,1024,NaN,NaN,NaN,NaN,NaN,NaN,0.012911,sequential

In [62]:
dataframe[-20:-10]

,executable,n_points,iter_limit,block_dim_x,block_dim_y,grid_dim_x,grid_dim_y,num_threads_per_block,num_blocks_per_grid,elapsed_time,version
380,cuda_heat,100,1024,90.509668,90.509668,2.093806,2.093806,8192.0,4.0,0.009463,cuda
381,cuda_heat,100,1024,90.509668,90.509668,2.093806,2.093806,8192.0,4.0,0.008982,cuda
382,cuda_heat,100,1024,90.509668,90.509668,2.093806,2.093806,8192.0,4.0,0.009243,cuda
383,cuda_heat,100,1024,90.509668,90.509668,2.093806,2.093806,8192.0,4.0,0.009386,cuda
384,cuda_heat,100,1024,90.509668,90.509668,2.093806,2.093806,8192.0,4.0,0.009381,cuda
385,cuda_heat,100,1024,90.509668,90.509668,2.093806,2.093806,8192.0,4.0,0.009481,cuda
386,cuda_heat,100,1024,90.509668,90.509668,2.093806,2.093806,8192.0,4.0,0.009431,cuda
387,cuda_heat,100,1024,90.509668,90.509668,2.093806,2.093806,8192.0,4.0,0.009431,cuda
388,cuda_heat,100,1024,90.509668,90.509668,2.093806,2.093806,8192.0,4.0,0.009524,cuda
389,cuda_heat,100,1024,90.509668,90.509668,2.093806,2.093806,8192.0,4.0,0.009404,cuda

In [ ]:
print(df.groupby("Executable")["Execution Time (s)"].mean())

In [40]:
paths_without_io = []
dataframes_without_io = []

for i in range(6):
    num_threads = 2**i
    dir_path = f"results_{num_threads}_threads"
    
    if i == 0:
        paths += get_file_paths(dir_path)
    else:
        paths += get_file_paths(dir_path, exclude_sequential=True)

    dataframes_without_io.append(read_and_parse_reports(paths, with_io=False, num_threads=num_threads))

dataframes_without_io[0].head()

,name,region,size,task_clock,CPUs_utilized,context_switches,cpu_migrations,page_faults,cycles,stalled_cycles_frontend,instructions,branches,branch_misses,time_elapsed,IO,num_threads
0,mandelbrot_pth,full,16,2.59,0.967,5,0,94,920.022,751.827,910.412,579.776,66.362,0.002683,False,1
1,mandelbrot_pth,full,32,2.72,0.956,5,0,99,152.222,653.608,793.929,687.049,67.340,0.0028398,False,1
2,mandelbrot_pth,full,64,2.98,1.121,3,0,130,382.302,012.397,403.526,138.260,75.758,0.002662,False,1
3,mandelbrot_pth,full,128,11.04,1.247,4,0,249,986.138,561.757,743.563,938.435,105.892,0.008859,False,1
4,mandelbrot_pth,full,256,30.54,1.379,3,0,729,514.931,577.487,042.793,119.646,223.916,0.02215,False,1

In [41]:
df_with_io = read_and_parse_reports(get_file_paths(), with_io=True, num_threads=16)
df_with_io.head()

,name,region,size,task_clock,CPUs_utilized,context_switches,cpu_migrations,page_faults,cycles,stalled_cycles_frontend,instructions,branches,branch_misses,time_elapsed,IO,num_threads
0,mandelbrot_pth,full,16,2.59,0.967,5,0,94,920.022,751.827,910.412,579.776,66.362,0.002683,True,16
1,mandelbrot_pth,full,32,2.72,0.956,5,0,99,152.222,653.608,793.929,687.049,67.340,0.0028398,True,16
2,mandelbrot_pth,full,64,2.98,1.121,3,0,130,382.302,012.397,403.526,138.260,75.758,0.002662,True,16
3,mandelbrot_pth,full,128,11.04,1.247,4,0,249,986.138,561.757,743.563,938.435,105.892,0.008859,True,16
4,mandelbrot_pth,full,256,30.54,1.379,3,0,729,514.931,577.487,042.793,119.646,223.916,0.02215,True,16

In [42]:
dfs = [df_with_io] + dataframes_without_io

In [43]:
final_df = pd.concat(dfs)

In [44]:
final_df.to_csv('final_results.csv', index=False)

In [45]:
df = pd.read_csv('final_results.csv')
df.sample(20)

,name,region,size,task_clock,CPUs_utilized,context_switches,cpu_migrations,page_faults,cycles,stalled_cycles_frontend,instructions,branches,branch_misses,time_elapsed,IO,num_threads
14246,mandelbrot_omp,full,1024,142.55,0.996,0,0,71,768.096,424.274,275.454,96.546,222.769,0.143180,False,16
1528,mandelbrot_pth,full,4096,486.64,8.056,217,23,143,247.702,261.697,508.393,716.925,108.064,0.308660,False,1
5486,mandelbrot_pth,full,1024,159.27,1.970,6,0,86,324.287,430.853,657.254,244.299,263.493,0.080830,False,2
17522,mandelbrot_pth,full,64,3.29,1.247,8,0,111,676.046,150.036,808.938,69.914,100.098,0.002637,False,32
14441,mandelbrot_omp,full,32,2.49,1.048,0,0,79,853.948,763.740,784.434,536.648,48.693,0.002374,False,16
14745,mandelbrot_pth,elephant,512,256.51,0.996,1,0,80,501.058,142.508,285.511,377.237,328.892,0.257440,False,16
1974,mandelbrot_pth,seahorse,256,82.34,9.764,21,2,111,968.571,926.935,660.196,414.801,194.941,0.008432,False,1
16629,mandelbrot_omp,elephant,8192,923.27,6.728,219,40,87,214.162,485.910,145.695,291.540,186.656,9.798100,False,16
4642,mandelbrot_omp,full,64,43.20,9.510,9,1,104,170.208,106.642,19.658,98.019,103.302,0.004542,False,2
9511,mandelbrot_pth,triple_spiral,32,4.66,1.609,14,0,144,741.512,719.553,873.313,778.924,146.909,0.002899,False,4
10333,mandelbrot_omp,seahorse,128,19.03,0.964,0,0,71,622.540,422.420,633.407,313.055,59.194,0.019744,False,8
16454,mandelbrot_omp,seahorse,256,79.35,1.865,1,0,74,978.867,364.584,236.165,906.337,128.579,0.042550,False,16
2389,mandelbrot_omp,elephant,8192,999.21,3.487,280,44,79,142.856,189.171,940.265,603.014,384.859,18.354200,False,1
5887,mandelbrot_seq,full,2048,555.24,0.999,1,0,59,709.760,851.414,787.474,674.693,703.327,0.555980,False,2
18384,mandelbrot_omp,elephant,256,78.48,1.843,2,0,74,947.567,868.687,58.412,89.872,123.973,0.042580,False,32
15330,mandelbrot_seq,seahorse,16,0.81,0.623,0,0,60,904.298,686.157,247.336,321.734,28.102,0.001297,False,16
19644,mandelbrot_omp,full,256,69.05,11.367,11,1,104,54.120,364.839,476.526,457.926,123.984,0.006074,False,32
13459,mandelbrot_seq,seahorse,8192,102.51,1.000,310,38,60,884.211,486.778,485.151,789.452,868.086,66.125700,False,16
6421,mandelbrot_seq,elephant,32,2.67,0.765,0,0,60,927.970,690.317,453.324,563.458,29.817,0.003487,False,2
6882,mandelbrot_omp,full,64,1.39,0.647,0,0,71,537.414,165.803,42.897,610.565,38.759,0.002141,False,4